version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/home/vlad/data/
    ports:
      - "4321:4321"
  data:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  db:

